package example

object BibleMp3Data {
  val ST = Seq(
    BibleFile("http://biblia-mp3.pl/Ksiega_Rodzaju.mp3", "Księga Rodzaju", "Rdz", "cała", "cała", "3:31:27", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Rodzaju_0_Wstep.mp3", "Księga Rodzaju", "Rdz", "podzielona", "Wstęp", "6:09", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Rodzaju_1-8.mp3", "Księga Rodzaju", "Rdz", "podzielona", "rozdziały 1-8", "27:52", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Rodzaju_9-18.mp3", "Księga Rodzaju", "Rdz", "podzielona", "rozdziały 9-18", "34:57", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Rodzaju_19-26.mp3", "Księga Rodzaju", "Rdz", "podzielona", "rozdziały 19-26", "39:17", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Rodzaju_27-33.mp3", "Księga Rodzaju", "Rdz", "podzielona", "rozdziały 27-33", "35:48", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Rodzaju_34-41.mp3", "Księga Rodzaju", "Rdz", "podzielona", "rozdziały 34-41", "37:18", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Rodzaju_42-50.mp3", "Księga Rodzaju", "Rdz", "podzielona", "rozdziały 42-50", "41:27", "Historyczne"),

    BibleFile("http://biblia-mp3.pl/Ksiega_Wyjscia.mp3", "Księga Wyjścia", "Wj", "cała", "cała", "2:57:34", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Wyjscia_0_Wstep.mp3", "Księga Wyjścia", "Wj", "podzielona", "Wstęp", "2:15", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Wyjscia_1-9.mp3", "Księga Wyjścia", "Wj", "podzielona", "rozdziały 1-9", "35:15", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Wyjscia_10-17.mp3", "Księga Wyjścia", "Wj", "podzielona", "rozdziały 10-17", "34:12", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Wyjscia_18-26.mp3", "Księga Wyjścia", "Wj", "podzielona", "rozdziały 18-26", "39:46", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Wyjscia_27-33.mp3", "Księga Wyjścia", "Wj", "podzielona", "rozdziały 27-33", "33:55", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Wyjscia_34-40.mp3", "Księga Wyjścia", "Wj", "podzielona", "rozdziały 34-40", "32:07", "Historyczne"),

    BibleFile("http://biblia-mp3.pl/Ksiega_Kaplanska.mp3", "Księga Kapłańska", "Kpł", "cała", "cała", "2:41:53", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Kaplanska_0_Wstep.mp3", "Księga Kapłańska", "Kpł", "podzielona", "Wstęp", "03:36", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Kaplanska_1-7.mp3", "Księga Kapłańska", "Kpł", "podzielona", "rozdziały 1-7", "32:11", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Kaplanska_8_13.mp3", "Księga Kapłańska", "Kpł", "podzielona", "rozdziały 8-13", "35:34", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Kaplanska_14_18.mp3", "Księga Kapłańska", "Kpł", "podzielona", "rozdziały 14-18", "30:58", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Kaplanska_19_24.mp3", "Księga Kapłańska", "Kpł", "podzielona", "rozdziały 19-24", "34:15", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Kaplanska_25_27.mp3", "Księga Kapłańska", "Kpł", "podzielona", "rozdziały 25-27", "25:14", "Historyczne"),

    BibleFile("http://biblia-mp3.pl/Ksiega_Liczb.mp3", "Księga Liczb", "Lb", "cała", "cała", "3:19:11", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Liczb_1_5.mp3", "Księga Liczb", "Lb", "podzielona", "rozdziały 1-5", "38:19", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Liczb_6_11.mp3", "Księga Liczb", "Lb", "podzielona", "rozdziały 6-11", "32:44", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Liczb_12_18.mp3", "Księga Liczb", "Lb", "podzielona", "rozdziały 12-18", "36:38", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Liczb_19_25.mp3", "Księga Liczb", "Lb", "podzielona", "rozdziały 19-25", "33:36", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Liczb_26_31.mp3", "Księga Liczb", "Lb", "podzielona", "rozdziały 23-31", "34:15", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Liczb_32_36.mp3", "Księga Liczb", "Lb", "podzielona", "rozdziały 32-36", "23:36", "Historyczne"),

    BibleFile("http://biblia-mp3.pl/Ksiega_Powtorzonego_Prawa.mp3", "Księga Powtórzonego Prawa", "Pwt", "cała", "cała", "3:04:15", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Powtorzonego_Prawa_1_3.mp3", "Księga Powtórzonego Prawa", "Pwt", "podzielona", "rozdziały 1-3", "32:12", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Powtorzonego_Prawa_4_9.mp3", "Księga Powtórzonego Prawa", "Pwt", "podzielona", "rozdziały 4-9", "32:08", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Powtorzonego_Prawa_10_16.mp3", "Księga Powtórzonego Prawa", "Pwt", "podzielona", "rozdziały 10-16", "32:40", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Powtorzonego_Prawa_17_25.mp3", "Księga Powtórzonego Prawa", "Pwt", "podzielona", "rozdziały 17-25", "36:34", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Powtorzonego_Prawa_26_30.mp3", "Księga Powtórzonego Prawa", "Pwt", "podzielona", "rozdziały 26-30", "28:28", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Powtorzonego_Prawa_31_34.mp3", "Księga Powtórzonego Prawa", "Pwt", "podzielona", "rozdziały 31-34", "22:08", "Historyczne"),

    BibleFile("http://biblia-mp3.pl/Ksiega_Jozuego.mp3", "Księga Jozuego", "Joz", "cała", "cała", "1:59:59 ", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Jozuego_0_Wstep.mp3", "Księga Jozuego", "Joz", "podzielona", "Wstęp", "5:01", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Jozuego_1-7.mp3", "Księga Jozuego", "Joz", "podzielona", "rozdziały 1-7", "30:38", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Jozuego_8-13.mp3", "Księga Jozuego", "Joz", "podzielona", "rozdziały 8-13", "33:58", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Jozuego_14-20.mp3", "Księga Jozuego", "Joz", "podzielona", "rozdziały 14-20", "31:09", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Jozuego_21-24.mp3", "Księga Jozuego", "Joz", "podzielona", "rozdziały 21-24", "22:32", "Historyczne"),

    BibleFile("http://biblia-mp3.pl/Ksiega_Sedziow.mp3", "Księga Sędziów", "Sdz", "cała", "cała", "01:59:14", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Sedziow_wstep.mp3", "Księga Sędziów", "Sdz", "podzielona", "wstęp", "13:58", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Sedziow_1_6.mp3", "Księga Sędziów", "Sdz", "podzielona", "rozdziały 1-6", "34:39", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Sedziow_7_11.mp3", "Księga Sędziów", "Sdz", "podzielona", "rozdziały 7-11", "34:01", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Sedziow_12_18.mp3", "Księga Sędziów", "Sdz", "podzielona", "rozdziały 12-18", "31:16", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Sedziow_19_21.mp3", "Księga Sędziów", "Sdz", "podzielona", "rozdziały 19-21", "19:16", "Historyczne"),

    BibleFile("http://biblia-mp3.pl/Ksiega_Rut.mp3", "Księga Rut", "Rt", "cała", "cała", "25:00", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Wstep_do_1_Ksiega_Samuela.mp3", "Pierwsza Księga Samuela", "Sm", "podzielona", "Wstęp do ksiąg Samuela", "04:52", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1_Ksiega_Samuela.mp3", "Pierwsza Księga Samuela", "1 Sm", "cała", "cała", "2:17:00", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1_Ksiega_Samuela_1-10.mp3", "Pierwsza Księga Samuela", "1 Sm", "podzielona", "rozdziały 1-10 ", "40:52", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1_Ksiega_Samuela_11-17.mp3", "Pierwsza Księga Samuela", "1 Sm", "podzielona", "rozdziały 11-17 ", "38:53", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1_Ksiega_Samuela_18-24.mp3", "Pierwsza Księga Samuela", "1 Sm", "podzielona", "rozdziały 18-24 ", "29:57", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1_Ksiega_Samuela_25-31.mp3", "Pierwsza Księga Samuela", "1 Sm", "podzielona", "rozdziały 25-31 ", "27:21", "Historyczne"),

    BibleFile("http://biblia-mp3.pl/2_Ksiega_Samuela.mp3", "Druga Księga Samuela", "2 Sm", "cała", "cała", "1:54:08", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/2_Ksiega_Samuela_1-10.mp3", "Druga Księga Samuela", "2 Sm", "podzielona", "rozdziały 1-10", "38:25", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/2_Ksiega_Samuela_11-17.mp3", "Druga Księga Samuela", "2 Sm", "podzielona", "rozdziały 11-17", "37:47  ", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/2_Ksiega_Samuela_18-24.mp3", "Druga Księga Samuela", "2 Sm", "podzielona", "rozdziały 18-24", "37:56", "Historyczne"),

    BibleFile("http://biblia-mp3.pl/1_0_2_Ksiegi_Krolewskie_Wstep.mp3", "Pierwsza Księga Królewska", "Krl", "podzielona", "wstęp do Ksiąg Królewskich", "22:13", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1_Ksiega_Krolewska.mp3", "Pierwsza Księga Królewska", "1 Krl", "cała", "cała", "2:22:56", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1_Ksiega_Krolewska_01_05.mp3", "Pierwsza Księga Królewska", "1 Krl", "podzielona", "rozdziały 1-5", "30:41", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1_Ksiega_Krolewska_06_09.mp3", "Pierwsza Księga Królewska", "1 Krl", "podzielona", "rozdziały 6-9", "31:13", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1_Ksiega_Krolewska_10_14.mp3", "Pierwsza Księga Królewska", "1 Krl", "podzielona", "rozdziały 10-14", "30:40", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1_Ksiega_Krolewska_15_19.mp3", "Pierwsza Księga Królewska", "1 Krl", "podzielona", "rozdziały 15-19", "28:09", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1_Ksiega_Krolewska_20_22.mp3", "Pierwsza Księga Królewska", "1 Krl", "podzielona", "rozdziały 20-22", "22:35", "Historyczne"),

    BibleFile("http://biblia-mp3.pl/2_Ksiega_Krolewska.mp3", "Druga Księga Królewska", "2 Krl", "cała", "cała", "2:17:14", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/2_Ksiega_Krolewska_01_06.mp3", "Druga Księga Królewska", "2 Krl", "podzielona", "rozdziały 1-6", "32:37", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/2_Ksiega_Krolewska_07_12.mp3", "Druga Księga Królewska", "2 Krl", "podzielona", "rozdziały 7-12", "32:02", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/2_Ksiega_Krolewska_13_18.mp3", "Druga Księga Królewska", "2 Krl", "podzielona", "rozdziały 13-18", "35:29", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/2_Ksiega_Krolewska_19_25.mp3", "Druga Księga Królewska", "2 Krl", "podzielona", "rozdziały 19-25", "37:08", "Historyczne"),

    BibleFile("http://biblia-mp3.pl/1_Ksiega_Kronik.mp3", "Pierwsza Księga Kronik", "1 Krn", "cała", "cała", "2:08:22", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1_Ksiega_Kronik_wstep.mp3", "Pierwsza Księga Kronik", "1 Krn", "podzielona", "wstęp", "5:11", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1_Ksiega_Kronik_1-6.mp3", "Pierwsza Księga Kronik", "1 Krn", "podzielona", "rozdziały 1-6", "34:44", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1_Ksiega_Kronik_7-12.mp3", "Pierwsza Księga Kronik", "1 Krn", "podzielona", "rozdziały 7-12", "30:00", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1_Ksiega_Kronik_13-20.mp3", "Pierwsza Księga Kronik", "1 Krn", "podzielona", "rozdziały 13-20", "25:12", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1_Ksiega_Kronik_21-29.mp3", "Pierwsza Księga Kronik", "1 Krn", "podzielona", "rozdziały 21-29", "38:24", "Historyczne"),

    BibleFile("http://biblia-mp3.pl/2_Ksiega_Kronik.mp3", "Druga Księga Kronik", "2 Krn", "cała", "cała", "2:27:55", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/2_Ksiega_Kronik_1-9.mp3", "Druga Księga Kronik", "2 Krn", "podzielona", "rozdziały 1-9", "35:51", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/2_Ksiega_Kronik_10-20.mp3", "Druga Księga Kronik", "2 Krn", "podzielona", "rozdziały 10-20", "38:10", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/2_Ksiega_Kronik_21-29.mp3", "Druga Księga Kronik", "2 Krn", "podzielona", "rozdziały 21-29", "37:34", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/2_Ksiega_Kronik_30-36.mp3", "Druga Księga Kronik", "2 Krn", "podzielona", "rozdziały 30-36", "36:18", "Historyczne"),

    BibleFile("http://biblia-mp3.pl/Wstep_Ezdrasz_i_Nehemiasz.mp3", "Księga Ezdrasza", "Ezd", "cała", "wstęp do Księgi Ezdrasza i Księgi Nehemiasza", "03:57", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Ezdrasza.mp3", "Księga Ezdrasza", "Ezd", "cała", "cała", "45:34", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Nehemiasza.mp3", "Księga Nehemiasza", "Ne", "cała", "cała", "1:05:16", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Nehemiasza_1_8.mp3", "Księga Nehemiasza", "Ne", "podzielona", "rozdziały 1-8", "34:24", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Nehemiasza_9_13.mp3", "Księga Nehemiasza", "Ne", "podzielona", "rozdziały 9-13", "30:51", "Historyczne"),

    BibleFile("http://biblia-mp3.pl/Ksiega_Tobiasza.mp3", "Księga Tobiasza", "Tb", "cała", "cała", "54:00", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Tobiasza_wstep.mp3", "Księga Tobiasza", "Tb", "podzielona", "wstęp", "01:56", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Tobiasza_1_8.mp3", "Księga Tobiasza", "Tb", "podzielona", "rozdziały 1-8", "34:07", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Tobiasza_9_14.mp3", "Księga Tobiasza", "Tb", "podzielona", "rozdziały 9-14", "19:53", "Historyczne"),

    BibleFile("http://biblia-mp3.pl/Ksiega_Judyty.mp3", "Księga Judyty", "Jdt", "cała", "cała", "1:01:58", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Judyty_wstep.mp3", "Księga Judyty", "Jdt", "podzielona", "wstęp", "03:19", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Judyty_1_9.mp3", "Księga Judyty", "Jdt", "podzielona", "rozdziały 1-9", "34:47", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Judyty_10_16.mp3", "Księga Judyty", "Jdt", "podzielona", "rozdziały 10-16", "27:11", "Historyczne"),

    BibleFile("http://biblia-mp3.pl/Ksiega_Estery.mp3", "Księga Estery", "Est", "cała", "cała", "49:23", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Estery_wstep.mp3", "Księga Estery", "Est", "podzielona", "wstęp", "03:01", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Estery_1_5.mp3", "Księga Estery", "Est", "podzielona", "rozdziały 1-5", "28:23", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Estery_6_10.mp3", "Księga Estery", "Est", "podzielona", "rozdziały 6-10", "20:59", "Historyczne"),

    BibleFile("http://biblia-mp3.pl/1Machabejska_calosc.mp3", "Pierwsza Księga Machabejska", "1 Mch", "cała", "cała", "2:03:00", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1Machabejska_wstep.mp3", "Pierwsza Księga Machabejska", "1 Mch", "podzielona", "Wstęp", "03:09", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1Machabejska_01-03.mp3", "Pierwsza Księga Machabejska", "1 Mch", "podzielona", "rozdziały 1-3", "26:26", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1Machabejska_04-07.mp3", "Pierwsza Księga Machabejska", "1 Mch", "podzielona", "rozdziały 4-7", "35:22", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1Machabejska_08-10.mp3", "Pierwsza Księga Machabejska", "1 Mch", "podzielona", "rozdziały 8-10", "32:05", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1Machabejska_11-13.mp3", "Pierwsza Księga Machabejska", "1 Mch", "podzielona", "rozdziały 11-13", "29:21", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/1Machabejska_14-16.mp3", "Pierwsza Księga Machabejska", "1 Mch", "podzielona", "rozdziały 14-16", "20:39", "Historyczne"),

    BibleFile("http://biblia-mp3.pl/2_Ksiega_Machabejska.mp3", "Druga Księga Machabejska", "2 Mch", "cała", "cała", "1:53:42", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/2_Ksiega_Machabejska_wstep.mp3", "Druga Księga Machabejska", "2 Mch", "podzielona", "wstęp", "03:47", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/2_Ksiega_Machabejska_1_4.mp3", "Druga Księga Machabejska", "2 Mch", "podzielona", "rozdziały 1-4", "29:31", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/2_Ksiega_Machabejska_5_9.mp3", "Druga Księga Machabejska", "2 Mch", "podzielona", "rozdziały 5-9", "32:50", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/2_Ksiega_Machabejska_10_13.mp3", "Druga Księga Machabejska", "2 Mch", "podzielona", "rozdziały 10-13", "28:05", "Historyczne"),
    BibleFile("http://biblia-mp3.pl/2_Ksiega_Machabejska_14_15.mp3", "Druga Księga Machabejska", "2 Mch", "podzielona", "rozdziały 14_15", "16:25", "Historyczne"),

    BibleFile("http://biblia-mp3.pl/Ksiega_Hioba.mp3", "Księga Hioba", "Hi", "cała", "cała", "2:45:31", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Hioba_00_wstep.mp3", "Księga Hioba", "Hi", "podzielona", "Wstęp ", "7:04", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Hioba_01-10.mp3", "Księga Hioba", "Hi", "podzielona", "rozdziały 1-10", "39:51", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Hioba_11-19.mp3", "Księga Hioba", "Hi", "podzielona", "rozdziały 11-19", "32:04", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Hioba_20-27.mp3", "Księga Hioba", "Hi", "podzielona", "rozdziały 20-27", "26:06", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Hioba_28-34.mp3", "Księga Hioba", "Hi", "podzielona", "rozdziały 28-34", "33:05", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Hioba_35-42.mp3", "Księga Hioba", "Hi", "podzielona", "rozdziały 35-42", "34:39", "Dydaktyczne"),

    BibleFile("http://biblia-mp3.pl/Ksiega_Psalmow.mp3", "Księga Psalmów", "Ps", "cała", "cała", "6:05:14", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Psalmy_1-18.mp3", "Księga Psalmów", "Ps", "podzielona", "psalmy 1-18", "35:47", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Psalmy_19-31.mp3", "Księga Psalmów", "Ps", "podzielona", "psalmy 19-31", "30:46", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Psalmy_32-42.mp3", "Księga Psalmów", "Ps", "podzielona", "psalmy 32-42", "33:04", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Psalmy_43-56.mp3", "Księga Psalmów", "Ps", "podzielona", "psalmy 43-56", "30:53", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Psalmy_57-69.mp3", "Księga Psalmów", "Ps", "podzielona", "psalmy 57-69", "31:23", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Psalmy_70-79.mp3", "Księga Psalmów", "Ps", "podzielona", "psalmy 70-79", "31:31", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Psalmy_80-91.mp3", "Księga Psalmów", "Ps", "podzielona", "psalmy 80-91", "31:01", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Psalmy_92-105.mp3", "Księga Psalmów", "Ps", "podzielona", "psalmy 92-105", "33:44", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Psalmy_106-118.mp3", "Księga Psalmów", "Ps", "podzielona", "psalmy 106-118", "32:23", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Psalmy_119-127.mp3", "Księga Psalmów", "Ps", "podzielona", "psalmy 119-127", "30:11", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Psalmy_128-144.mp3", "Księga Psalmów", "Ps", "podzielona", "psalmy 128-144", "31:37", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Psalmy_145-150.mp3", "Księga Psalmów", "Ps", "podzielona", "psalmy 145-150", "11:33", "Dydaktyczne"),

    BibleFile("http://biblia-mp3.pl/Ksiega_Przyslow.mp3", "Księga Przysłów", "Prz", "cała", "cała", "1:35:30", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Przyslow_01_11.mp3", "Księga Przysłów", "Prz", "podzielona", "rozdziały 1-11", "30:33", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Przyslow_12_20.mp3", "Księga Przysłów", "Prz", "podzielona", "rozdziały 12-20", "29:36", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Przyslow_21_31.mp3", "Księga Przysłów", "Prz", "podzielona", "rozdziały 21-31", "35:23", "Dydaktyczne"),

    BibleFile("http://biblia-mp3.pl/Ksiega_Koheleta.mp3", "Księga Koheleta (Eklezjastesa)", "Koh", "cała", "cała", "47:13", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Koheleta_0_Wstep.mp3", "Księga Koheleta (Eklezjastesa)", "Koh", "podzielona", "Wstęp", "6:03", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Koheleta_rozdzialy_1-8.mp3", "Księga Koheleta (Eklezjastesa)", "Koh", "podzielona", "rozdziały 1-8", "33:07", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Koheleta_rozdzialy_9-12.mp3", "Księga Koheleta (Eklezjastesa)", "Koh", "podzielona", "rozdziały 9-12", "14:11", "Dydaktyczne"),

    BibleFile("http://biblia-mp3.pl/Piesn_Nad_Piesniami.mp3", "Pieśń nad Pieśniami", "Pnp", "cała", "cała", "27:32", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Madrosci.mp3", "Księga Mądrości", "Mdr", "cała", "cała", "1:19:28", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Madrosci_rozdzialy_01-09.mp3", "Księga Mądrości", "Mdr", "podzielona", "rozdziały 1-9", "30:59", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Madrosci_rozdzialy_10-15.mp3", "Księga Mądrości", "Mdr", "podzielona", "rozdziały 10-15", "25:13", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Madrosci_rozdzialy_16-19.mp3", "Księga Mądrości", "Mdr", "podzielona", "rozdziały 16-19", "18:19", "Dydaktyczne"),

    BibleFile("http://biblia-mp3.pl/Madrosc_Syracha.mp3", "Mądrość Syracha (Eklezjastyk)", "Syr", "cała", "cała", "3:53:21", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Madrosc_Syracha_rozdzialy_01-07.mp3", "Mądrość Syracha (Eklezjastyk)", "Syr", "podzielona", "rozdziały 1-7", "33:04", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Madrosc_Syracha_rozdzialy_08-15.mp3", "Mądrość Syracha (Eklezjastyk)", "Syr", "podzielona", "rozdziały 8-15", "31:47", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Madrosc_Syracha_rozdzialy_16-23.mp3", "Mądrość Syracha (Eklezjastyk)", "Syr", "podzielona", "rozdziały 16-23", "37:15", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Madrosc_Syracha_rozdzialy_24-30.mp3", "Mądrość Syracha (Eklezjastyk)", "Syr", "podzielona", "rozdziały 24-30", "29:35", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Madrosc_Syracha_rozdzialy_31-37.mp3", "Mądrość Syracha (Eklezjastyk)", "Syr", "podzielona", "rozdziały 31-37", "30:14", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Madrosc_Syracha_rozdzialy_38-43.mp3", "Mądrość Syracha (Eklezjastyk)", "Syr", "podzielona", "rozdziały 38-43", "32:25", "Dydaktyczne"),
    BibleFile("http://biblia-mp3.pl/Madrosc_Syracha_rozdzialy_44-51.mp3", "Mądrość Syracha (Eklezjastyk)", "Syr", "podzielona", "rozdziały 44-51", "35:34", "Dydaktyczne"),

    BibleFile("http://biblia-mp3.pl/Ksiega_Izajasza.mp3", "Księga Izajasza", "Iz", "cała", "cała", "3:41:08", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Izajasza_0_wstep.mp3", "Księga Izajasza", "Iz", "podzielona", "Wstęp", "9:02", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Izajasza_rozdzialy_1-10.mp3", "Księga Izajasza", "Iz", "podzielona", "rozdziały 1-10", "35:31", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Izajasza_rozdzialy_11-22.mp3", "Księga Izajasza", "Iz", "podzielona", "rozdziały 11-22", "31:17", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Izajasza_rozdzialy_23-31.mp3", "Księga Izajasza", "Iz", "podzielona", "rozdziały 23-31", "30:50", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Izajasza_rozdzialy_32-40.mp3", "Księga Izajasza", "Iz", "podzielona", "rozdziały 32-40", "31:03", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Izajasza_rozdzialy_41-48.mp3", "Księga Izajasza", "Iz", "podzielona", "rozdziały 41-48", "32:39", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Izajasza_rozdzialy_49-58.mp3", "Księga Izajasza", "Iz", "podzielona", "rozdziały 49-58", "31:45", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Izajasza_rozdzialy_59-66.mp3", "Księga Izajasza", "Iz", "podzielona", "rozdziały 59-66", "28:05", "Profetyczne"),

    BibleFile("http://biblia-mp3.pl/Ksiega_Jeremiasza.mp3", "Księga Jeremiasza", "Jr", "cała", "cała", "4:03:58", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Jeremiasza_00_wstep.mp3", "Księga Jeremiasza", "Jr", "podzielona", "Wstęp", "6:27", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Jeremiasza_01-06.mp3", "Księga Jeremiasza", "Jr", "podzielona", "rozdziały 1-6", "31:05", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Jeremiasza_07-14.mp3", "Księga Jeremiasza", "Jr", "podzielona", "rozdziały 7-14", "34:24", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Jeremiasza_15-23.mp3", "Księga Jeremiasza", "Jr", "podzielona", "rozdziały 15-23", "38:54", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Jeremiasza_24-31.mp3", "Księga Jeremiasza", "Jr", "podzielona", "rozdziały 24-31", "36:36", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Jeremiasza_32-38.mp3", "Księga Jeremiasza", "Jr", "podzielona", "rozdziały 32-38", "34:34", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Jeremiasza_39-47.mp3", "Księga Jeremiasza", "Jr", "podzielona", "rozdziały 39-47", "29:57", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Jeremiasza_48-52.mp3", "Księga Jeremiasza", "Jr", "podzielona", "rozdziały 48-52", "38:55", "Profetyczne"),

    BibleFile("http://biblia-mp3.pl/Lamentacje.mp3", "Lamentacje", "Lm", "cała", "cała", "20:07", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Lamentacje_wstep.mp3", "Lamentacje", "Lm", "cała", "Wstęp", "3:46", "Profetyczne"),

    BibleFile("http://biblia-mp3.pl/Ksiega_Barucha.mp3", "Księga Barucha", "Ba", "cała", "cała", "29:27", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Barucha_wstep.mp3", "Księga Barucha", "Ba", "cała", "Wstęp", "5:04", "Profetyczne"),

    BibleFile("http://biblia-mp3.pl/Ezechiel_calosc.mp3", "Księga Ezechiela", "Ez", "cała", "cała", "3:34:05", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ezechiel_wstep.mp3", "Księga Ezechiela", "Ez", "podzielona", "wstęp", "08:20", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ezechiel_01-10.mp3", "Księga Ezechiela", "Ez", "podzielona", "rozdziały 1-10", "31:53", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ezechiel_11-17.mp3", "Księga Ezechiela", "Ez", "podzielona", "rozdziały 11-17", "31:11", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ezechiel_18-23.mp3", "Księga Ezechiela", "Ez", "podzielona", "rozdziały 18-23", "33:02", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ezechiel_24-31.mp3", "Księga Ezechiela", "Ez", "podzielona", "rozdziały 24-31", "31:20", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ezechiel_32-37.mp3", "Księga Ezechiela", "Ez", "podzielona", "rozdziały 32-37", "30:30", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ezechiel_38-43.mp3", "Księga Ezechiela", "Ez", "podzielona", "rozdziały 38-43", "29:42", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ezechiel_44-48.mp3", "Księga Ezechiela", "Ez", "podzielona", "rozdziały 44-48", "26:41", "Profetyczne"),

      BibleFile("http://biblia-mp3.pl/Ksiega_Daniela.mp3", "Księga Daniela", "Dn", "cała", "cała", "1:26:13", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Daniel_wstep.mp3", "Księga Daniela", "Dn", "podzielona", "wstęp", "4:53", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Daniel_01-04.mp3", "Księga Daniela", "Dn", "podzielona", "rozdziały 1-4", "32:59", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Daniel_05-09.mp3", "Księga Daniela", "Dn", "podzielona", "rozdziały 5-9", "25:33", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Daniel_10-14.mp3", "Księga Daniela", "Dn", "podzielona", "rozdziały 10-14", "27:46", "Profetyczne"),

    BibleFile("http://biblia-mp3.pl/Ksiega_Ozeasza.mp3", "Księga Ozeasza", "Oz", "cała", "cała", "35:08", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Joela.mp3", "Księga Joela", "Jl", "cała", "cała", "14:14", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Amosa.mp3", "Księga Amosa", "Am", "cała", "cała", "26:29", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Abdiasza.mp3", "Księga Abdiasza", "Ab", "cała", "cała", "4:51", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Jonasza.mp3", "Księga Jonasza", "Jon", "cała", "cała", "11:01", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Micheasza.mp3", "Księga Micheasza", "Mi", "cała", "cała", "25:00", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Nahuma.mp3", "Księga Nahuma", "Na", "cała", "cała", "12:33", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Habakuka.mp3", "Księga Habakuka", "Ha", "cała", "cała", "12:42", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Sofoniasza.mp3", "Księga Sofoniasza", "So", "cała", "cała", "13:27", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Aggeusza.mp3", "Księga Aggeusza", "Ag", "cała", "cała", "6:55", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Zachariasza.mp3", "Księga Zachariasza", "Za", "cała", "cała", "43:27", "Profetyczne"),
    BibleFile("http://biblia-mp3.pl/Ksiega_Malachiasza.mp3", "Księga Malachiasza", "Ml", "cała", "cała", "17:31", "Profetyczne"),
  )

  val NT = Seq(
    BibleFile("http://biblia-mp3.pl/Ewangelia_Mateusza.mp3", "Ewangelia według św. Mateusza", "Mt", "cała", "cała", "2:52:04", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Mateusza_1-7.mp3", "Ewangelia według św. Mateusza", "Mt", "podzielona", "rozdziały 1-7", "34:31", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Mateusza_8-12.mp3", "Ewangelia według św. Mateusza", "Mt", "podzielona", "rozdziały 8-12", "31:49", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Mateusza_13-17.mp3", "Ewangelia według św. Mateusza", "Mt", "podzielona", "rozdziały 13-17", "29:53", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Mateusza_18-22.mp3", "Ewangelia według św. Mateusza", "Mt", "podzielona", "rozdziały 18-22", "30:38", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Mateusza_23-26.mp3", "Ewangelia według św. Mateusza", "Mt", "podzielona", "rozdziały 23-26", "32:19", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Mateusza_27-28.mp3", "Ewangelia według św. Mateusza", "Mt", "podzielona", "rozdziały 27-28", "12:52", "Ewangelie"),

    BibleFile("http://biblia-mp3.pl/Ewangelia_Marka.mp3", "Ewangelia według św. Marka", "Mk", "cała", "cała", "1:46:45", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Marka_1-5.mp3", "Ewangelia według św. Marka", "Mk", "podzielona", "rozdziały 1-5", "28:45", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Marka_6-9.mp3", "Ewangelia według św. Marka", "Mk", "podzielona", "rozdziały 6-9", "28:38", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Marka_10-13.mp3", "Ewangelia według św. Marka", "Mk", "podzielona", "rozdziały 10-13", "27:49", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Marka_14-16.mp3", "Ewangelia według św. Marka", "Mk", "podzielona", "rozdziały 14-16", "21:29", "Ewangelie"),

    BibleFile("http://biblia-mp3.pl/Ewangelia_Lukasza.mp3", "Ewangelia według św. Łukasza", "Łk", "cała", "cała", "2:55:13", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Lukasza_1-4.mp3", "Ewangelia według św. Łukasza", "Łk", "podzielona", "rozdziały 1-4", "30:16", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Lukasza_5-8.mp3", "Ewangelia według św. Łukasza", "Łk", "podzielona", "rozdziały 5-8", "33:16", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Lukasza_9-12.mp3", "Ewangelia według św. Łukasza", "Łk", "podzielona", "rozdziały 9-12", "35:38", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Lukasza_13-18.mp3", "Ewangelia według św. Łukasza", "Łk", "podzielona", "rozdziały 13-18", "32:29", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Lukasza_19-22.mp3", "Ewangelia według św. Łukasza", "Łk", "podzielona", "rozdziały 19-22", "28:14", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Lukasza_23-24.mp3", "Ewangelia według św. Łukasza", "Łk", "podzielona", "rozdziały 23-24", "15:17", "Ewangelie"),

    BibleFile("http://biblia-mp3.pl/Ewangelia_Jana.mp3", "Ewangelia według św. Jana", "J", "cała", "cała", "2:18:24", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Jana_1-5.mp3", "Ewangelia według św. Jana", "J", "podzielona", "rozdziały 1-5", "34:09", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Jana_6-9.mp3", "Ewangelia według św. Jana", "J", "podzielona", "rozdziały 6-9", "33:36", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Jana_10-15.mp3", "Ewangelia według św. Jana", "J", "podzielona", "rozdziały 10-15", "36:50", "Ewangelie"),
    BibleFile("http://biblia-mp3.pl/Ewangelia_Jana_16-21.mp3", "Ewangelia według św. Jana", "J", "podzielona", "rozdziały 16-21", "33:47", "Ewangelie"),

    BibleFile("http://biblia-mp3.pl/Dzieje_Apostolskie.mp3", "Dzieje Apostolskie", "Dz", "cała", "całe", "2:32:07", "Dzieje Apostolskie"),
    BibleFile("http://biblia-mp3.pl/Dzieje_Apostolskie_1_7.mp3", "Dzieje Apostolskie", "Dz", "podzielona", "rozdziały 1-7", "38:02", "Dzieje Apostolskie"),
    BibleFile("http://biblia-mp3.pl/Dzieje_Apostolskie_8_13.mp3", "Dzieje Apostolskie", "Dz", "podzielona", "rozdziały 8-13", "33:45", "Dzieje Apostolskie"),
    BibleFile("http://biblia-mp3.pl/Dzieje_Apostolskie_14_19.mp3", "Dzieje Apostolskie", "Dz", "podzielona", "rozdziały 14-19", "32:30", "Dzieje Apostolskie"),
    BibleFile("http://biblia-mp3.pl/Dzieje_Apostolskie_20_25.mp3", "Dzieje Apostolskie", "Dz", "podzielona", "rozdziały 20-25", "31:20", "Dzieje Apostolskie"),
    BibleFile("http://biblia-mp3.pl/Dzieje_Apostolskie_26_28.mp3", "Dzieje Apostolskie", "Dz", "podzielona", "rozdziały 26-28", "16:30", "Dzieje Apostolskie"),

    BibleFile("http://biblia-mp3.pl/List_Do_Rzymian.mp3", "List do Rzymian", "Rz", "cała", "cały", "1:17:52", "Listy Pawłowe"),
    BibleFile("http://biblia-mp3.pl/List_Do_Rzymian_1-8.mp3", "List do Rzymian", "Rz", "podzielona", "rozdziały 1-8", "41:08", "Listy Pawłowe"),
    BibleFile("http://biblia-mp3.pl/List_Do_Rzymian_9-16.mp3", "List do Rzymian", "Rz", "podzielona", "rozdziały 9-16", "36:44", "Listy Pawłowe"),

    BibleFile("http://biblia-mp3.pl/1_List_do_Koryntian.mp3", "1 List do Koryntian", "1 Kor", "cała", "cały", "1:12:27", "Listy Pawłowe"),
    BibleFile("http://biblia-mp3.pl/1_List_do_Koryntian_1_9.mp3", "1 List do Koryntian", "1 Kor", "podzielona", "rozdziały 1-9", "35:57", "Listy Pawłowe"),
    BibleFile("http://biblia-mp3.pl/1_List_do_Koryntian_10_16.mp3", "1 List do Koryntian", "1 Kor", "podzielona", "rozdziały 10-16", "36:30", "Listy Pawłowe"),

    BibleFile("http://biblia-mp3.pl/2_List_Do_Koryntian.mp3", "2 List do Koryntian", "2 Kor", "cała", "cały", "44:19", "Listy Pawłowe"),
    BibleFile("http://biblia-mp3.pl/List_Do_Galatow.mp3", "List do Galatów", "Ga", "cała", "cały", "24:18", "Listy Pawłowe"),
    BibleFile("http://biblia-mp3.pl/List_Do_Efezjan.mp3", "List do Efezjan", "Ef", "cała", "cały", "23:05", "Listy Pawłowe"),
    BibleFile("http://biblia-mp3.pl/List_Do_Filipian.mp3", "List do Filipian", "Flp", "cała", "cały", "16:10", "Listy Pawłowe"),
    BibleFile("http://biblia-mp3.pl/List_Do_Kolosan.mp3", "List do Kolosan", "Kol", "cała", "cały", "17:09", "Listy Pawłowe"),
    BibleFile("http://biblia-mp3.pl/1_List_Do_Tesaloniczan.mp3", "1 List do Tesaloniczan", "1 Tes", "cała", "cały", "13:12", "Listy Pawłowe"),
    BibleFile("http://biblia-mp3.pl/2_List_Do_Tesaloniczan.mp3", "2 List do Tesaloniczan", "2 Tes", "cała", "cały", "8:09", "Listy Pawłowe"),
    BibleFile("http://biblia-mp3.pl/1_List_Do_Tymoteusza.mp3", "1 List do Tymoteusza", "1 Tm", "cała", "cały", "18:36", "Listy Pawłowe"),
    BibleFile("http://biblia-mp3.pl/2_List_Do_Tymoteusza.mp3", "2 List do Tymoteusza", "2 Tm", "cała", "cały", "14:22", "Listy Pawłowe"),
    BibleFile("http://biblia-mp3.pl/List_Do_Tytusa.mp3", "List do Tytusa", "Tt", "cała", "cały", "7:49", "Listy Pawłowe"),
    BibleFile("http://biblia-mp3.pl/List_Do_Filemona.mp3", "List do Filemona", "Flm", "cała", "cały", "03:24", "Listy Pawłowe"),
    BibleFile("http://biblia-mp3.pl/List_Do_Hebrajczykow.mp3", "List do Hebrajczyków", "Hbr", "cała", "cały", "53:46", "Listy Pawłowe"),
    BibleFile("http://biblia-mp3.pl/List_do_Hebrajczykow_1_7.mp3", "List do Hebrajczyków", "Hbr", "podzielona", "rozdziały 1-7", "23:18", "Listy Pawłowe"),
    BibleFile("http://biblia-mp3.pl/List_do_Hebrajczykow_8_13.mp3", "List do Hebrajczyków", "Hbr", "podzielona", "rozdziały 8-13", "30:30", "Listy Pawłowe"),

    BibleFile("http://biblia-mp3.pl/List_Jakuba.mp3", "List św. Jakuba Apostoła", "Jk", "cała", "cały", "17:48", "Listy"),
    BibleFile("http://biblia-mp3.pl/1_List_Piotra.mp3", "1 List św. Piotra Apostoła", "1 P", "cała", "cały", "22:07", "Listy"),
    BibleFile("http://biblia-mp3.pl/2_List_Piotra.mp3", "2 List św. Piotra Apostoła", "2 P", "cała", "cały", "11:30", "Listy"),
    BibleFile("http://biblia-mp3.pl/1_List_Jana.mp3", "1 List św. Jana Apostoła", "1 J", "cała", "cały", "21:34", "Listy"),
    BibleFile("http://biblia-mp3.pl/2_List_Jana.mp3", "2 List św. Jana Apostoła", "2 J", "cała", "cały", "2:13", "Listy"),
    BibleFile("http://biblia-mp3.pl/3_List_Jana.mp3", "3 List św. Jana Apostoła", "3 J", "cała", "cały", "2:35", "Listy"),
    BibleFile("http://biblia-mp3.pl/List_Judy.mp3", "List św. Judy Apostoła", "Jud", "cała", "cały", "5:05", "Listy"),

    BibleFile("http://biblia-mp3.pl/Apokalipsa_Jana.mp3", "Apokalipsa św. Jana", "Ap", "cała", "cały", "1:28:15", "Apokalipsa"),
    BibleFile("http://biblia-mp3.pl/Apokalipsa_Jana_1_7.mp3", "Apokalipsa św. Jana", "Ap", "podzielona", "rozdziały 1-7", "30:10", "Apokalipsa"),
    BibleFile("http://biblia-mp3.pl/Apokalipsa_Jana_8_16.mp3", "Apokalipsa św. Jana", "Ap", "podzielona", "rozdziały 8-16", "31:50", "Apokalipsa"),
    BibleFile("http://biblia-mp3.pl/Apokalipsa_Jana_17_22.mp3", "Apokalipsa św. Jana", "Ap", "podzielona", "rozdziały 17-22", "26:55", "Apokalipsa")
  )
}
